title: TSA Reference
description: An open resource for learning about TSA
baseurl: "/TSA-Reference"
url: "https://j-nac.github.io/"

remote_theme: pmarsceill/just-the-docs

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/j-nac/TSA-Reference"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"
