title: TSA Reference
description: An open resource for learning about TSA
baseurl: "/TSA-Reference"
url: "https://j-nac.github.io/"

remote_theme: pmarsceill/just-the-docs

aux_links:
  "TSA Reference on GitHub":
    - "//github.com/j-nac/TSA-Reference"

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e, %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/j-nac/TSA-Reference"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"
